# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9f24b11d9ce2f8dbf17e2c7f5346a28e30798a111de4ee76dfcb26eb48ec84c8bd83d9152d5ae5f7b5c3279062a1cee74e2c8a41fd63916a2348a127cddebdd

test:
  secret_key_base: 7a9ce8019f72d1583383744d8798117517b24706474c8fa0935815a94fef8f065db52287e0ebce32ce490658db1e666636d25d7f38a5d56ce1671897ea0f89ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
